# Generated by Django 5.2.16 on 2026-07-23 11:53

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0009_onboardingprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('chatbot', 'Site-wide chatbot'), ('concierge', 'Founder concierge'), ('funding_plan', 'Funding plan')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('scope_key', models.CharField(editable=False, max_length=36)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('max_turns', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('agent', 'Agent'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='assistant.agentsession')),
            ],
            options={
                'ordering': ['sequence_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied')], max_length=20)),
                ('input_params', models.JSONField(blank=True, default=dict)),
                ('authorization_context', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_hash', models.CharField(max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tool_call_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_call_logs', to='assistant.agentsession')),
                ('triggering_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_tool_calls', to='assistant.agentmessage')),
            ],
            options={
                'ordering': ['sequence_number', 'called_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentClaimReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_key', models.CharField(max_length=150)),
                ('claim_text', models.TextField()),
                ('output_path', models.CharField(max_length=500)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_references', to='assistant.agentmessage')),
                ('tool_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_references', to='assistant.agenttoolcalllog')),
            ],
            options={
                'ordering': ['message__sequence_number', 'claim_key'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['founder', 'agent_type', 'status'], name='agent_session_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['startup_profile', 'agent_type'], name='agent_session_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('founder', 'agent_type', 'scope_key'), name='unique_active_agent_session_scope'),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.CheckConstraint(condition=models.Q(('turn_count__lte', models.F('max_turns'))), name='agent_session_turns_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'active')), models.Q(('completed_at__isnull', False), ('status__in', ['completed', 'abandoned'])), _connector='OR'), name='agent_session_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='agentmessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='unique_agent_message_sequence'),
        ),
        migrations.AddConstraint(
            model_name='agentmessage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='agent_message_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='agenttoolcalllog',
            index=models.Index(fields=['session', 'tool_name', 'called_at'], name='agent_tool_call_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoolcalllog',
            index=models.Index(fields=['status', 'called_at'], name='agent_tool_call_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolcalllog',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='unique_agent_tool_call_sequence'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolcalllog',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='agent_tool_call_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentclaimreference',
            constraint=models.UniqueConstraint(fields=('message', 'claim_key'), name='unique_agent_message_claim_key'),
        ),
    ]
