# Generated by Django 5.2.16 on 2026-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='copilot_context',
            field=models.JSONField(blank=True, default=dict, help_text='Active workspace context injected by the Universal AI Copilot.'),
        ),
    ]
