from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from apps.accounts.views import (
    CurrentUserView,
    FounderRegistrationView,
)
from apps.assistant.copilot_context_views import CopilotContextView
from apps.assistant.views import (
    ChatbotCurrentView,
    ChatbotMessageCreateView,
    ConciergeCurrentView,
    ConciergeDraftUpdateView,
    ConciergeTransitionView,
)
from apps.core.views import HealthView, PlatformStatusView
from apps.discovery.views import (
    CrawlFrontierEntryViewSet,
    CrawlFrontierView,
    DiscoveredURLViewSet,
    DocumentQualityAssessmentViewSet,
)
from apps.documents.views import (
    DocumentChunkViewSet,
    DocumentExtractionViewSet,
    ProcessDocumentView,
)
from apps.recommendations.tracker_views import SchemeApplicationTrackerViewSet
from apps.recommendations.verification_reviewer_views import (
    EligibilityVerificationReviewerDecisionCreateView,
    EligibilityVerificationReviewerEvidenceDownloadView,
    EligibilityVerificationReviewerQueueView,
)
from apps.recommendations.verification_views import (
    EligibilityVerificationEvidenceUploadView,
    EligibilityVerificationGateListView,
    EligibilityVerificationSubmissionCreateView,
)
from apps.recommendations.views import (
    EligibilityEvaluateView,
    RecommendationCurrentView,
    RecommendationGenerateView,
    RecommendationRunDetailView,
    RecommendationRunListView,
)
from apps.schemes.views import SchemeViewSet
from apps.sources.views import (
    CrawlRunViewSet,
    SourceDocumentViewSet,
    SourceViewSet,
)
from apps.startups.advisor_views import (
    StartupAdvisorBriefingCurrentView,
    StartupAdvisorBriefingDetailView,
    StartupAdvisorBriefingGenerateView,
    StartupAdvisorBriefingJobCurrentView,
    StartupAdvisorBriefingJobDetailView,
    StartupAdvisorBriefingListView,
    StartupAdvisorCurrentView,
    StartupAdvisorSnapshotGenerateView,
)
from apps.startups.assessment_views import (
    StartupAssessmentDraftSubmitView,
    StartupAssessmentDraftViewSet,
)
from apps.startups.builder_consultant_views import MasterConsultantGeneratorView
from apps.startups.builder_views import (
    StartupBuilderSectionDetailView,
    StartupBuilderSectionDraftView,
    StartupBuilderSectionListView,
)
from apps.startups.capital_planner_views import (
    StartupCapitalPlanCurrentView,
    StartupCapitalPlanGenerateView,
)
from apps.startups.milestone_views import (
    StartupMilestoneCompleteView,
    StartupMilestoneDetailView,
    StartupMilestoneListCreateView,
    StartupMilestoneLogUpdateView,
)
from apps.startups.onboarding_views import (
    StartupOnboardingCurrentView,
)
from apps.startups.startup_intelligence_views import StartupIntelligenceView
from apps.startups.startup_resume_views import StartupResumeGeneratorView
from apps.startups.verification_sandbox_views import InstantVerificationSandboxView
from apps.startups.views import (
    StartupFundingPlanCurrentView,
    StartupFundingPlanDetailView,
    StartupFundingPlanGenerateView,
    StartupFundingPlanListView,
    StartupProfileDocumentAutofillView,
    StartupProfileViewSet,
    StartupReadinessActionPlanCurrentView,
    StartupReadinessActionPlanDetailView,
    StartupReadinessActionPlanGenerateView,
    StartupReadinessActionPlanListView,
    StartupReadinessAssessmentDetailView,
    StartupReadinessAssessmentListView,
    StartupReadinessCurrentView,
    StartupReadinessEvaluateView,
    StartupStartingPlanCurrentView,
    StartupStartingPlanDetailView,
    StartupStartingPlanGenerateView,
    StartupStartingPlanListView,
)

router = DefaultRouter()
router.register("sources", SourceViewSet, basename="source")
router.register(
    "source-documents",
    SourceDocumentViewSet,
    basename="source-document",
)
router.register("crawl-runs", CrawlRunViewSet, basename="crawl-run")
router.register(
    "document-extractions",
    DocumentExtractionViewSet,
    basename="document-extraction",
)
router.register(
    "document-chunks",
    DocumentChunkViewSet,
    basename="document-chunk",
)
router.register(
    "discovered-urls",
    DiscoveredURLViewSet,
    basename="discovered-url",
)
router.register(
    "crawl-frontier",
    CrawlFrontierEntryViewSet,
    basename="crawl-frontier-entry",
)
router.register(
    "document-quality",
    DocumentQualityAssessmentViewSet,
    basename="document-quality",
)
router.register(
    r"tracker-applications",
    SchemeApplicationTrackerViewSet,
    basename="tracker-application",
)
router.register(r"schemes", SchemeViewSet, basename="scheme")
router.register(
    "startup-profiles",
    StartupProfileViewSet,
    basename="startup-profile",
)
router.register(
    "startup-assessment-drafts",
    StartupAssessmentDraftViewSet,
    basename="startup-assessment-draft",
)


urlpatterns = [
    path(
        "api/v1/assistant/concierge/current/",
        ConciergeCurrentView.as_view(),
        name="assistant-concierge-current",
    ),
    path(
        "api/v1/assistant/concierge/current/updates/",
        ConciergeDraftUpdateView.as_view(),
        name="assistant-concierge-draft-update",
    ),
    path(
        "api/v1/assistant/concierge/current/transitions/",
        ConciergeTransitionView.as_view(),
        name="assistant-concierge-transition",
    ),
    path(
        "api/v1/assistant/chatbot/current/",
        ChatbotCurrentView.as_view(),
        name="assistant-chatbot-current",
    ),
    path(
        "api/v1/assistant/chatbot/current/messages/",
        ChatbotMessageCreateView.as_view(),
        name="assistant-chatbot-message-create",
    ),
    path(
        "api/v1/assistant/chatbot/current/copilot-context/",
        CopilotContextView.as_view(),
        name="assistant-chatbot-copilot-context",
    ),
    path(
        "api/v1/auth/register/",
        FounderRegistrationView.as_view(),
        name="founder-register",
    ),
    path(
        "api/v1/auth/me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path("admin/", admin.site.urls),
    path(
        "api/schema/",
        SpectacularAPIView.as_view(),
        name="schema",
    ),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/v1/health/", HealthView.as_view(), name="health"),
    path(
        "api/v1/status/",
        PlatformStatusView.as_view(),
        name="platform-status",
    ),
    path(
        "api/v1/auth/token/",
        TokenObtainPairView.as_view(),
        name="token-obtain",
    ),
    path(
        "api/v1/auth/token/refresh/",
        TokenRefreshView.as_view(),
        name="token-refresh",
    ),
    path(
        "api/v1/startup-advisor/briefings/generate/",
        StartupAdvisorBriefingGenerateView.as_view(),
        name="startup-advisor-briefing-generate",
    ),
    path(
        "api/v1/startup-advisor/briefings/jobs/current/",
        StartupAdvisorBriefingJobCurrentView.as_view(),
        name="startup-advisor-briefing-job-current",
    ),
    path(
        "api/v1/startup-advisor/briefings/jobs/<uuid:job_id>/",
        StartupAdvisorBriefingJobDetailView.as_view(),
        name="startup-advisor-briefing-job-detail",
    ),
    path(
        "api/v1/startup-advisor/briefings/current/",
        StartupAdvisorBriefingCurrentView.as_view(),
        name="startup-advisor-briefing-current",
    ),
    path(
        "api/v1/startup-advisor/briefings/",
        StartupAdvisorBriefingListView.as_view(),
        name="startup-advisor-briefing-list",
    ),
    path(
        "api/v1/startup-advisor/briefings/<uuid:briefing_id>/",
        StartupAdvisorBriefingDetailView.as_view(),
        name="startup-advisor-briefing-detail",
    ),
    path(
        "api/v1/startup-advisor/current/",
        StartupAdvisorCurrentView.as_view(),
        name="startup-advisor-current",
    ),
    path(
        "api/v1/startup-advisor/snapshots/generate/",
        StartupAdvisorSnapshotGenerateView.as_view(),
        name="startup-advisor-snapshot-generate",
    ),
    path(
        "api/v1/startup-onboarding/current/",
        StartupOnboardingCurrentView.as_view(),
        name="startup-onboarding-current",
    ),
    path(
        "api/v1/startup-profiles/autofill-from-document/",
        StartupProfileDocumentAutofillView.as_view(),
        name="startup-profile-autofill-from-document",
    ),
    path(
        "api/v1/startup-assessment-drafts/<uuid:draft_id>/submit/",
        StartupAssessmentDraftSubmitView.as_view(),
        name="startup-assessment-draft-submit",
    ),
    path(
        "api/v1/startup-readiness/evaluate/",
        StartupReadinessEvaluateView.as_view(),
        name="startup-readiness-evaluate",
    ),
    path(
        "api/v1/startup-readiness/current/",
        StartupReadinessCurrentView.as_view(),
        name="startup-readiness-current",
    ),
    path(
        "api/v1/startup-readiness/assessments/",
        StartupReadinessAssessmentListView.as_view(),
        name="startup-readiness-assessment-list",
    ),
    path(
        "api/v1/startup-readiness/assessments/<uuid:assessment_id>/",
        StartupReadinessAssessmentDetailView.as_view(),
        name="startup-readiness-assessment-detail",
    ),
    path(
        "api/v1/startup-readiness/action-plans/generate/",
        StartupReadinessActionPlanGenerateView.as_view(),
        name="startup-readiness-action-plan-generate",
    ),
    path(
        "api/v1/startup-readiness/action-plans/current/",
        StartupReadinessActionPlanCurrentView.as_view(),
        name="startup-readiness-action-plan-current",
    ),
    path(
        "api/v1/startup-readiness/action-plans/",
        StartupReadinessActionPlanListView.as_view(),
        name="startup-readiness-action-plan-list",
    ),
    path(
        "api/v1/startup-funding-plans/generate/",
        StartupFundingPlanGenerateView.as_view(),
        name="startup-funding-plan-generate",
    ),
    path(
        "api/v1/startup-funding-plans/current/",
        StartupFundingPlanCurrentView.as_view(),
        name="startup-funding-plan-current",
    ),
    path(
        "api/v1/startup-funding-plans/",
        StartupFundingPlanListView.as_view(),
        name="startup-funding-plan-list",
    ),
    path(
        "api/v1/startup-funding-plans/<uuid:funding_plan_id>/",
        StartupFundingPlanDetailView.as_view(),
        name="startup-funding-plan-detail",
    ),
    path(
        "api/v1/startup-starting-plans/generate/",
        StartupStartingPlanGenerateView.as_view(),
        name="startup-starting-plan-generate",
    ),
    path(
        "api/v1/startup-starting-plans/current/",
        StartupStartingPlanCurrentView.as_view(),
        name="startup-starting-plan-current",
    ),
    path(
        "api/v1/startup-starting-plans/",
        StartupStartingPlanListView.as_view(),
        name="startup-starting-plan-list",
    ),
    path(
        "api/v1/startup-starting-plans/<uuid:starting_plan_id>/",
        StartupStartingPlanDetailView.as_view(),
        name="startup-starting-plan-detail",
    ),
    path(
        "api/v1/startup-readiness/action-plans/<uuid:action_plan_id>/",
        StartupReadinessActionPlanDetailView.as_view(),
        name="startup-readiness-action-plan-detail",
    ),
    path(
        "api/v1/eligibility/evaluate/",
        EligibilityEvaluateView.as_view(),
        name="eligibility-evaluate",
    ),
    path(
        "api/v1/eligibility/verifications/reviewer/submissions/",
        EligibilityVerificationReviewerQueueView.as_view(),
        name="eligibility-verification-reviewer-queue",
    ),
    path(
        ("api/v1/eligibility/verifications/reviewer/submissions/<uuid:submission_id>/decisions/"),
        EligibilityVerificationReviewerDecisionCreateView.as_view(),
        name=("eligibility-verification-reviewer-decision-create"),
    ),
    path(
        ("api/v1/eligibility/verifications/reviewer/evidence/<uuid:evidence_id>/download/"),
        EligibilityVerificationReviewerEvidenceDownloadView.as_view(),
        name=("eligibility-verification-reviewer-evidence-download"),
    ),
    path(
        "api/v1/eligibility/verifications/gates/",
        EligibilityVerificationGateListView.as_view(),
        name="eligibility-verification-gate-list",
    ),
    path(
        "api/v1/eligibility/verifications/submissions/",
        EligibilityVerificationSubmissionCreateView.as_view(),
        name="eligibility-verification-submission-create",
    ),
    path(
        ("api/v1/eligibility/verifications/submissions/<uuid:submission_id>/evidence/"),
        EligibilityVerificationEvidenceUploadView.as_view(),
        name="eligibility-verification-evidence-upload",
    ),
    path(
        "api/v1/recommendations/generate/",
        RecommendationGenerateView.as_view(),
        name="recommendation-generate",
    ),
    path(
        "api/v1/startup-builder/generate-master-plan/",
        MasterConsultantGeneratorView.as_view(),
        name="startup-builder-generate-master-plan",
    ),
    path(
        "api/v1/startup-builder/generate-resume/",
        StartupResumeGeneratorView.as_view(),
        name="startup-builder-generate-resume",
    ),
    path(
        "api/v1/startups/verify-instant/",
        InstantVerificationSandboxView.as_view(),
        name="startup-verify-instant",
    ),
    path(
        "api/v1/recommendations/current/",
        RecommendationCurrentView.as_view(),
        name="recommendation-current",
    ),
    path(
        "api/v1/recommendations/runs/",
        RecommendationRunListView.as_view(),
        name="recommendation-run-list",
    ),
    path(
        "api/v1/recommendations/runs/<uuid:run_id>/",
        RecommendationRunDetailView.as_view(),
        name="recommendation-run-detail",
    ),
    path(
        "api/v1/documents/process/",
        ProcessDocumentView.as_view(),
        name="process-document",
    ),
    path(
        "api/v1/discovery/crawl/",
        CrawlFrontierView.as_view(),
        name="crawl-frontier",
    ),
    path(
        "api/v1/knowledge/",
        include("apps.knowledge.urls"),
    ),
    path(
        "api/v1/startup-builder/sections/",
        StartupBuilderSectionListView.as_view(),
        name="startup-builder-section-list",
    ),
    path(
        "api/v1/startup-builder/sections/<str:section_type>/",
        StartupBuilderSectionDetailView.as_view(),
        name="startup-builder-section-detail",
    ),
    path(
        "api/v1/startup-builder/sections/<str:section_type>/draft/",
        StartupBuilderSectionDraftView.as_view(),
        name="startup-builder-section-draft",
    ),
    path(
        "api/v1/startup-capital-plans/current/",
        StartupCapitalPlanCurrentView.as_view(),
        name="startup-capital-plan-current",
    ),
    path(
        "api/v1/startup-capital-plans/generate/",
        StartupCapitalPlanGenerateView.as_view(),
        name="startup-capital-plan-generate",
    ),
    path(
        "api/v1/startup-milestones/",
        StartupMilestoneListCreateView.as_view(),
        name="startup-milestone-list-create",
    ),
    path(
        "api/v1/startup-milestones/<uuid:milestone_id>/",
        StartupMilestoneDetailView.as_view(),
        name="startup-milestone-detail",
    ),
    path(
        "api/v1/startup-milestones/<uuid:milestone_id>/complete/",
        StartupMilestoneCompleteView.as_view(),
        name="startup-milestone-complete",
    ),
    path(
        "api/v1/startup-milestones/<uuid:milestone_id>/log-update/",
        StartupMilestoneLogUpdateView.as_view(),
        name="startup-milestone-log-update",
    ),
    path(
        "api/v1/startups/<uuid:profile_id>/intelligence/",
        StartupIntelligenceView.as_view(),
        name="startup-intelligence",
    ),
    path("api/v1/", include(router.urls)),
]
