# Generated by Django 5.2.16 on 2026-07-20 06:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ministry', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('official_domain', models.CharField(max_length=255, unique=True)),
                ('listing_url', models.URLField(max_length=1000)),
                ('application_portal_url', models.URLField(blank=True, max_length=1000)),
                ('authority_tier', models.CharField(choices=[('A', 'A - Official programme portal or notification'), ('B', 'B - Ministry, department or implementing agency'), ('C', 'C - Government aggregator'), ('D', 'D - Authorised delivery partner'), ('E', 'E - Discovery only')], max_length=1)),
                ('crawl_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='weekly', max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(max_length=1500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_key', models.CharField(blank=True, max_length=1000)),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('retrieved_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('extracted', 'Extracted'), ('review_required', 'Review required'), ('verified', 'Verified'), ('failed', 'Failed')], default='collected', max_length=32)),
                ('extractor_version', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='sources.source')),
            ],
            options={
                'ordering': ['-retrieved_at'],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'content_hash'), name='unique_source_document_version')],
            },
        ),
    ]
