# Generated by Django 5.2.16 on 2026-07-20 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API')], default='manual', max_length=20)),
                ('requested_url', models.URLField(max_length=1500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partially succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('documents_created', models.PositiveIntegerField(default=0)),
                ('documents_unchanged', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='sourcedocument',
            name='unique_source_document_version',
        ),
        migrations.AddField(
            model_name='source',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='source',
            name='max_document_bytes',
            field=models.PositiveIntegerField(default=26214400),
        ),
        migrations.AddField(
            model_name='source',
            name='request_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='source',
            name='respect_robots_txt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='content_length',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='etag',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='final_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='last_modified',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='sources.sourcedocument'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_runs', to='sources.source'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='crawl_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.crawlrun'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['source_url', 'is_current'], name='sources_sou_source__d152cc_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['source', '-retrieved_at'], name='sources_sou_source__9310d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('source_url', 'version_number'), name='unique_source_url_version_number'),
        ),
    ]
