# Generated by Django 5.2.16 on 2026-07-27 11:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0015_ml_engine_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('requires_live_search', models.BooleanField(default=False)),
                ('search_decision_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=128)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=2000)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.CharField(blank=True, default='', max_length=64)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(default='unverified_live', max_length=64)),
                ('content_excerpt', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('verification_status', models.CharField(choices=[('verified_internal', 'Verified Internal'), ('official_live', 'Official Live'), ('reputable_secondary', 'Reputable Secondary'), ('unverified_live', 'Unverified Live'), ('rejected', 'Rejected')], default='unverified_live', max_length=64)),
                ('research_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='research.researchrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchSearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('provider', models.CharField(default='tavily', max_length=64)),
                ('result_count', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('research_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='research.researchrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartupResearchReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_data_cutoff', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_search_date', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=128)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=64)),
                ('report', models.JSONField(default=dict)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('research_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='research.researchrequest')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
