# Generated by Django 5.2.16 on 2026-07-20 06:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('likely_eligible', 'Likely eligible'), ('conditionally_eligible', 'Conditionally eligible'), ('insufficient_information', 'Insufficient information'), ('verification_required', 'Verification required'), ('application_closed', 'Application closed')], max_length=40)),
                ('matched_rules', models.JSONField(default=list)),
                ('failed_rules', models.JSONField(default=list)),
                ('unknown_rules', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('engine_version', models.CharField(default='rules-v1', max_length=50)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='schemes.schemeversion')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='startups.startupprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=6, max_digits=7)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommendations.eligibilityassessment')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schemes.schemeversion')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='startups.startupprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
