# Generated by Django 5.2.16 on 2026-07-23 05:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0004_recommendation_generation_runs"),
        ("schemes", "0002_authorityalias"),
        ("startups", "0008_startupassessmentdraft_race_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityVerificationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                ("claim_value", models.JSONField(blank=True, null=True)),
                ("claim_text", models.TextField(blank=True)),
                (
                    "eligibility_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_submissions",
                        to="schemes.eligibilityrule",
                    ),
                ),
                (
                    "scheme_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_verification_submissions",
                        to="schemes.schemeversion",
                    ),
                ),
                (
                    "startup_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_verification_submissions",
                        to="startups.startupprofile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibility_verification_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_submissions",
                        to="recommendations.eligibilityverificationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["startup_profile", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityVerificationEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("storage_key", models.CharField(max_length=1000, unique=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibility_verification_evidence_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="recommendations.eligibilityverificationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityVerificationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")], max_length=20
                    ),
                ),
                ("verified_value", models.JSONField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("submission_snapshot", models.JSONField(default=dict)),
                ("rule_snapshot", models.JSONField(default=dict)),
                ("evidence_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_verification_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="recommendations.eligibilityverificationsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="eligibilityverificationsubmission",
            index=models.Index(
                fields=["startup_profile", "is_current", "-created_at"],
                name="elig_ver_profile_current",
            ),
        ),
        migrations.AddIndex(
            model_name="eligibilityverificationsubmission",
            index=models.Index(
                fields=["eligibility_rule", "is_current", "-created_at"],
                name="elig_ver_rule_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilityverificationsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("startup_profile", "eligibility_rule"),
                name="unique_current_eligibility_verification",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilityverificationevidence",
            constraint=models.UniqueConstraint(
                fields=("submission", "content_hash"), name="unique_submission_evidence_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="eligibilityverificationdecision",
            index=models.Index(
                fields=["submission", "-created_at"], name="elig_ver_decision_latest"
            ),
        ),
        migrations.AddIndex(
            model_name="eligibilityverificationdecision",
            index=models.Index(
                fields=["outcome", "valid_from", "expires_on"], name="elig_ver_decision_validity"
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilityverificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "approved"), ("verified_value__isnull", False)),
                    models.Q(("outcome", "rejected"), ("verified_value__isnull", True)),
                    _connector="OR",
                ),
                name="elig_ver_decision_value_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilityverificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_on__isnull", True),
                    ("expires_on__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="elig_ver_decision_dates_valid",
            ),
        ),
    ]
