# Generated by Django 5.2.16 on 2026-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_eligibility_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='ml_score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of the blended ML+heuristic score components.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='svm_score',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='SVM-predicted probability of scheme acquisition success (0.0–1.0).', max_digits=7, null=True),
        ),
    ]
