# Generated by Django 5.2.16 on 2026-07-25 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_ml_engine_integration'),
        ('schemes', '0003_schemegraphprojectionrun_prerequisiteconcept_and_more'),
        ('startups', '0015_ml_engine_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved / Granted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submission_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application_data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_applications', to=settings.AUTH_USER_MODEL)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_applications', to='schemes.schemeversion')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_applications', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('startup_profile', 'scheme_version'), name='unique_startup_scheme_tracker_application')],
            },
        ),
    ]
