# Generated by Django 5.2.16 on 2026-07-20 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('incorporation_type', models.CharField(blank=True, max_length=100)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('validation', 'Problem validation'), ('prototype', 'Prototype'), ('mvp', 'Minimum viable product'), ('pilot', 'Pilot'), ('early_revenue', 'Early revenue'), ('growth', 'Growth'), ('expansion', 'Expansion')], max_length=32)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('founder_categories', models.JSONField(blank=True, default=list)),
                ('founder_gender', models.CharField(blank=True, max_length=50)),
                ('dpiit_recognized', models.BooleanField(blank=True, null=True)),
                ('udyam_registered', models.BooleanField(blank=True, null=True)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue_stage', models.CharField(blank=True, max_length=100)),
                ('funding_required', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('funding_purpose', models.TextField(blank=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['startup_name'],
            },
        ),
    ]
