# Generated by Django 5.2.16 on 2026-07-21 07:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0004_recommendation_generation_runs"),
        ("startups", "0003_startupreadinessactionplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupAdvisorSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_readiness_assessment", models.BooleanField()),
                ("has_action_plan", models.BooleanField()),
                ("has_recommendation_generation", models.BooleanField()),
                ("profile_snapshot", models.JSONField(default=dict)),
                ("readiness_snapshot", models.JSONField(default=dict)),
                ("action_plan_snapshot", models.JSONField(default=dict)),
                ("recommendation_generation_snapshot", models.JSONField(default=dict)),
                ("recommendations_snapshot", models.JSONField(default=list)),
                ("recommendation_count", models.PositiveIntegerField(default=0)),
                (
                    "snapshot_version",
                    models.CharField(default="startup-advisor-snapshot-v1", max_length=64),
                ),
                (
                    "readiness_action_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisor_snapshots",
                        to="startups.startupreadinessactionplan",
                    ),
                ),
                (
                    "readiness_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisor_snapshots",
                        to="startups.startupreadinessassessment",
                    ),
                ),
                (
                    "recommendation_generation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisor_snapshots",
                        to="recommendations.recommendationgenerationrun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startup_advisor_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_snapshots",
                        to="startups.startupprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["startup_profile", "-created_at"],
                        name="startup_adv_profile_created",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("has_readiness_assessment", True),
                                ("readiness_assessment__isnull", False),
                            ),
                            models.Q(
                                ("has_readiness_assessment", False),
                                ("readiness_assessment__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="startup_adv_readiness_match",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("has_action_plan", True), ("readiness_action_plan__isnull", False)
                            ),
                            models.Q(
                                ("has_action_plan", False), ("readiness_action_plan__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="startup_adv_action_match",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("has_recommendation_generation", True),
                                ("recommendation_generation_run__isnull", False),
                            ),
                            models.Q(
                                ("has_recommendation_generation", False),
                                ("recommendation_count", 0),
                                ("recommendation_generation_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="startup_adv_generation_match",
                    ),
                ],
            },
        ),
    ]
