# Generated by Django 5.2.16 on 2026-07-21 07:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0004_startup_advisor_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupAdvisorBriefing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=255)),
                ("prompt_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("generation_parameters", models.JSONField(default=dict)),
                ("prompt_snapshot", models.JSONField(default=dict)),
                ("briefing", models.JSONField(default=dict)),
                ("prompt_token_count", models.PositiveIntegerField(blank=True, null=True)),
                ("output_token_count", models.PositiveIntegerField(blank=True, null=True)),
                ("total_duration_ns", models.PositiveBigIntegerField(blank=True, null=True)),
                ("response_metadata", models.JSONField(default=dict)),
                ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startup_advisor_briefings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="briefings",
                        to="startups.startupadvisorsnapshot",
                    ),
                ),
                (
                    "startup_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_briefings",
                        to="startups.startupprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["startup_profile", "-created_at"], name="st_brief_profile_created"
                    ),
                    models.Index(
                        fields=["source_snapshot", "-created_at"], name="st_brief_source_created"
                    ),
                ],
            },
        ),
    ]
