# Generated by Django 5.2.16 on 2026-07-21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0005_startup_advisor_briefing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupAssessmentDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "submitted_profile_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startup_assessment_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_drafts",
                        to="startups.startupprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-updated_at"],
                        name="startup_draft_owner_updated",
                    ),
                    models.Index(
                        fields=["startup_profile", "-updated_at"],
                        name="startup_draft_profile_updated",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_step__gte", 1),
                            ("current_step__lte", 8),
                        ),
                        name="startup_draft_step_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("startup_profile__isnull", False),
                            ("status", "draft"),
                        ),
                        fields=("owner", "startup_profile"),
                        name="startup_one_draft_per_profile",
                    ),
                ],
            },
        ),
    ]
