# Generated by Django 5.2.16 on 2026-07-21 19:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startupassessmentdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAdvisorBriefingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('briefing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='startups.startupadvisorbriefing')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_advisor_briefing_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefing_jobs', to='startups.startupadvisorsnapshot')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_briefing_jobs', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['startup_profile', '-created_at'], name='st_brief_job_profile_created'), models.Index(fields=['status', '-created_at'], name='st_brief_job_status_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('startup_profile',), name='st_brief_one_active_job'), models.CheckConstraint(condition=models.Q(models.Q(('briefing__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', True), ('status', 'queued')), models.Q(('briefing__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'running')), models.Q(('briefing__isnull', False), ('completed_at__isnull', False), ('started_at__isnull', False), ('status', 'succeeded')), models.Q(('briefing__isnull', True), ('completed_at__isnull', False), ('status', 'failed')), _connector='OR'), name='st_brief_job_state_match')],
            },
        ),
    ]
