# Generated by Django 5.2.16 on 2026-07-23 10:22

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_startupassessmentdraft_race_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_version', models.CharField(default='founder-onboarding-v1', max_length=64)),
                ('variant', models.CharField(choices=[('empty_profile', 'Empty profile'), ('returning_founder', 'Returning founder')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='active', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_step__gte', 1), ('current_step__lte', 4)), name='startup_onboarding_step_range')],
            },
        ),
    ]
