# Generated by Django 5.2.16 on 2026-07-23 18:00

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_eligibility_verification'),
        ('startups', '0009_onboardingprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupStartingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('readiness_snapshot', models.JSONField(default=dict)),
                ('action_plan_snapshot', models.JSONField(default=dict)),
                ('recommendation_generation_snapshot', models.JSONField(default=dict)),
                ('recommendations_snapshot', models.JSONField(default=list)),
                ('readiness_item_count', models.PositiveIntegerField(default=0)),
                ('recommendation_item_count', models.PositiveIntegerField(default=0)),
                ('total_item_count', models.PositiveIntegerField(default=0)),
                ('next_item', models.JSONField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('plan_version', models.CharField(default='startup-starting-plan-v1', max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('recommendation_generation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_plans', to='recommendations.recommendationgenerationrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_starting_plans', to=settings.AUTH_USER_MODEL)),
                ('source_action_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_plans', to='startups.startupreadinessactionplan')),
                ('source_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_plans', to='startups.startupreadinessassessment')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_plans', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['startup_profile', '-created_at'], name='startup_start_profile_created')],
                'constraints': [models.UniqueConstraint(fields=('source_action_plan', 'recommendation_generation_run'), name='startup_unique_starting_plan_sources'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('startup_profile',), name='startup_unique_current_starting_plan'), models.CheckConstraint(condition=models.Q(('total_item_count', django.db.models.expressions.CombinedExpression(models.F('readiness_item_count'), '+', models.F('recommendation_item_count')))), name='startup_start_plan_counts_match'), models.CheckConstraint(condition=models.Q(models.Q(('next_item__isnull', True), ('total_item_count', 0)), models.Q(('next_item__isnull', False), ('total_item_count__gt', 0)), _connector='OR'), name='startup_start_plan_next_match')],
            },
        ),
    ]
