# Generated by Django 5.2.16 on 2026-07-24 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_startupstartingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupFundingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('dependency_count', models.PositiveIntegerField(default=0)),
                ('execution_wave_count', models.PositiveIntegerField(default=0)),
                ('next_step_ids', models.JSONField(default=list)),
                ('plan_version', models.CharField(default='startup-funding-plan-v1', max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_funding_plans', to=settings.AUTH_USER_MODEL)),
                ('source_starting_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_plans', to='startups.startupstartingplan')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_plans', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['startup_profile', '-created_at'], name='startup_fund_profile_created'), models.Index(fields=['source_starting_plan', 'source_hash'], name='startup_fund_source_hash')],
                'constraints': [models.UniqueConstraint(fields=('source_starting_plan', 'as_of_date', 'source_hash', 'plan_version'), name='startup_unique_funding_source'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('startup_profile',), name='startup_unique_current_funding')],
            },
        ),
    ]
