# Generated by Django 5.2.16 on 2026-07-24 10:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0011_startup_funding_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupBuilderSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('problem', 'Problem Definition'), ('customer', 'Target Customer'), ('interviews', 'Customer Interview Planning'), ('validation', 'Validation Experiments'), ('business_model', 'Business Model'), ('pricing', 'Pricing Strategy'), ('mvp', 'MVP Planning'), ('sales', 'Sales & Distribution'), ('hiring', 'Hiring & Management'), ('legal', 'Legal & Compliance Planning'), ('funding_strategy', 'Funding Strategy'), ('milestones', 'Execution Milestones')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_drafted', 'AI Drafted'), ('confirmed', 'Confirmed')], default='draft', max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('ai_draft', models.JSONField(blank=True, default=dict)),
                ('plan_version', models.CharField(default='startup-builder-v1', max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_builder_sections', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_sections', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['section_type'],
                'indexes': [models.Index(fields=['startup_profile', 'section_type'], name='builder_section_profile_type')],
                'constraints': [models.UniqueConstraint(fields=('startup_profile', 'section_type'), name='builder_one_section_per_type')],
            },
        ),
    ]
