# Generated by Django 5.2.16 on 2026-07-24 11:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_startup_builder_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupCapitalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fixed_costs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variable_costs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_burn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('runway_months', models.DecimalField(decimal_places=1, max_digits=8)),
                ('runway_status', models.CharField(choices=[('critical', 'Critical (< 6 months)'), ('caution', 'Caution (6–18 months)'), ('healthy', 'Healthy (> 18 months)')], max_length=16)),
                ('scenarios', models.JSONField(default=dict)),
                ('allocations', models.JSONField(default=dict)),
                ('sensitivity', models.JSONField(default=dict)),
                ('ai_explanation', models.JSONField(blank=True, default=dict)),
                ('plan_version', models.CharField(default='startup-capital-plan-v1', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_capital_plans', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_plans', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['startup_profile', '-created_at'], name='capital_plan_profile_created')],
            },
        ),
    ]
