# Generated by Django 5.2.16 on 2026-07-24 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0013_startup_capital_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('product', 'Product & MVP'), ('funding', 'Funding & Grants'), ('compliance', 'Compliance & Legal'), ('sales', 'Sales & Distribution'), ('hiring', 'Hiring & Team')], default='product', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('linked_scheme_id', models.UUIDField(blank=True, null=True)),
                ('linked_builder_section', models.CharField(blank=True, max_length=64)),
                ('completion_evidence', models.JSONField(blank=True, default=dict)),
                ('updates_log', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_version', models.CharField(default='startup-milestone-v1', max_length=64)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='startups.startupmilestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_milestones', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['target_date', '-created_at'],
                'indexes': [models.Index(fields=['startup_profile', 'status'], name='milestone_profile_status')],
            },
        ),
    ]
