# Generated by Django 5.2.16 on 2026-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0014_startup_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='anomaly_score',
            field=models.FloatField(blank=True, help_text='Isolation Forest anomaly score. Negative values indicate anomalies.', null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='is_anomalous',
            field=models.BooleanField(default=False, help_text='Flagged as anomalous by the Isolation Forest model.'),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='ml_cohort_id',
            field=models.IntegerField(blank=True, help_text='K-Means cohort assigned by the ML engine.', null=True),
        ),
    ]
