# Generated by Django 5.2.16 on 2026-07-20 09:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('sources', '0002_crawlrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=2000)),
                ('normalized_url', models.URLField(max_length=2000)),
                ('anchor_text', models.CharField(blank=True, max_length=1000)),
                ('page_type', models.CharField(choices=[('landing', 'Landing page'), ('listing', 'Listing page'), ('category', 'Category page'), ('scheme_detail', 'Scheme detail'), ('loan_detail', 'Loan detail'), ('registration_detail', 'Registration detail'), ('certificate_detail', 'Certificate detail'), ('benefit_detail', 'Benefit detail'), ('incubator_detail', 'Incubator detail'), ('application_page', 'Application page'), ('guideline_pdf', 'Guideline PDF'), ('policy_pdf', 'Policy PDF'), ('faq', 'FAQ'), ('sitemap', 'Sitemap'), ('api_endpoint', 'API endpoint'), ('login', 'Login or account page'), ('error', 'Error page'), ('asset', 'Non-content asset'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('discovery_method', models.CharField(choices=[('seed', 'Seed URL'), ('html_link', 'HTML link'), ('pdf_link', 'PDF link'), ('embedded_json', 'Embedded JSON'), ('sitemap', 'Sitemap'), ('manual', 'Manual')], default='html_link', max_length=30)),
                ('crawl_depth', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('queued', 'Queued'), ('collected', 'Collected'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='discovered', max_length=20)),
                ('allowed', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('provisional_quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_collected_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_origins', to='sources.sourcedocument')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_urls', to='sources.sourcedocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_urls', to='sources.source')),
            ],
            options={
                'ordering': ['priority', 'crawl_depth', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlFrontierEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('discovered_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontier_entry', to='discovery.discoveredurl')),
            ],
            options={
                'ordering': ['discovered_url__priority', 'scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('landing', 'Landing page'), ('listing', 'Listing page'), ('category', 'Category page'), ('scheme_detail', 'Scheme detail'), ('loan_detail', 'Loan detail'), ('registration_detail', 'Registration detail'), ('certificate_detail', 'Certificate detail'), ('benefit_detail', 'Benefit detail'), ('incubator_detail', 'Incubator detail'), ('application_page', 'Application page'), ('guideline_pdf', 'Guideline PDF'), ('policy_pdf', 'Policy PDF'), ('faq', 'FAQ'), ('sitemap', 'Sitemap'), ('api_endpoint', 'API endpoint'), ('login', 'Login or account page'), ('error', 'Error page'), ('asset', 'Non-content asset'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('positive_signals', models.JSONField(blank=True, default=list)),
                ('negative_signals', models.JSONField(blank=True, default=list)),
                ('usable_for_discovery', models.BooleanField(default=False)),
                ('usable_for_rag', models.BooleanField(default=False)),
                ('usable_for_structured_extraction', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assessor_version', models.CharField(default='v1', max_length=50)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='documents.documentextraction')),
            ],
            options={
                'ordering': ['-score', '-assessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['status', 'priority', 'crawl_depth'], name='discovery_d_status_46372d_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['source', 'page_type'], name='discovery_d_source__e4bd3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveredurl',
            constraint=models.UniqueConstraint(fields=('source', 'normalized_url'), name='unique_discovered_source_url'),
        ),
        migrations.AddIndex(
            model_name='crawlfrontierentry',
            index=models.Index(fields=['status', 'scheduled_at'], name='discovery_c_status_fc216f_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlfrontierentry',
            index=models.Index(fields=['next_retry_at'], name='discovery_c_next_re_505c43_idx'),
        ),
        migrations.AddIndex(
            model_name='documentqualityassessment',
            index=models.Index(fields=['page_type', '-score'], name='discovery_d_page_ty_4a6629_idx'),
        ),
        migrations.AddIndex(
            model_name='documentqualityassessment',
            index=models.Index(fields=['usable_for_structured_extraction', '-score'], name='discovery_d_usable__d79814_idx'),
        ),
    ]
