# Generated by Django 5.2.16 on 2026-07-20 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('authority_type', models.CharField(blank=True, max_length=100)),
                ('ministry', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('official_url', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=150)),
                ('alternative_names', models.JSONField(blank=True, default=list)),
                ('lifecycle_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='schemes.authority')),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('support_types', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('eligible_sectors', models.JSONField(blank=True, default=list)),
                ('eligible_stages', models.JSONField(blank=True, default=list)),
                ('eligible_states', models.JSONField(blank=True, default=list)),
                ('founder_categories', models.JSONField(blank=True, default=list)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('equity_required', models.BooleanField(blank=True, null=True)),
                ('interest_rate_min', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('interest_rate_max', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('application_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('rolling', 'Rolling'), ('upcoming', 'Upcoming'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_url', models.URLField(max_length=1500)),
                ('application_url', models.URLField(blank=True, max_length=1500)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('application_steps', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('extracted', 'Extracted'), ('review_required', 'Review required'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='extracted', max_length=32)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemes.scheme')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_versions', to='sources.sourcedocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scheme_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheme', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='scheme',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_schemes', to='schemes.schemeversion'),
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_path', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('in', 'In'), ('not_in', 'Not in'), ('greater_than', 'Greater than'), ('greater_or_equal', 'Greater than or equal'), ('less_than', 'Less than'), ('less_or_equal', 'Less than or equal'), ('between', 'Between'), ('contains_any', 'Contains any'), ('contains_all', 'Contains all'), ('exists', 'Exists'), ('not_exists', 'Does not exist')], max_length=32)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('rule_group', models.CharField(blank=True, max_length=100)),
                ('evidence_text', models.TextField()),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('manually_verified', models.BooleanField(default=False)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['scheme_version', 'rule_group', 'field_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='schemeversion',
            constraint=models.UniqueConstraint(fields=('scheme', 'version_number'), name='unique_scheme_version_number'),
        ),
        migrations.AddConstraint(
            model_name='schemeversion',
            constraint=models.UniqueConstraint(fields=('scheme', 'content_hash'), name='unique_scheme_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='scheme',
            constraint=models.UniqueConstraint(fields=('canonical_name', 'authority'), name='unique_scheme_authority'),
        ),
    ]
