# Generated by Django 5.2.16 on 2026-07-20 15:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=500)),
                ('normalized_alias', models.CharField(max_length=500, unique=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='schemes.authority')),
            ],
            options={
                'ordering': ['normalized_alias'],
            },
        ),
    ]
