# Generated by Django 5.2.16 on 2026-07-23 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_authorityalias'),
        ('sources', '0002_crawlrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeGraphProjectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scheme_node_count', models.PositiveIntegerField(default=0)),
                ('prerequisite_node_count', models.PositiveIntegerField(default=0)),
                ('prerequisite_edge_count', models.PositiveIntegerField(default=0)),
                ('unlock_edge_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('certification', 'Certification'), ('compliance', 'Compliance'), ('financial', 'Financial readiness'), ('operational', 'Operational readiness'), ('scheme_access', 'Scheme access'), ('other', 'Other')], default='other', max_length=40)),
                ('lifecycle_status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('retired', 'Retired')], default='draft', max_length=30)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_concepts', to='sources.sourcedocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prerequisite_concepts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('extracted', 'Extracted'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('review_status', models.CharField(choices=[('review_required', 'Review required'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='review_required', max_length=30)),
                ('evidence_text', models.TextField()),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requirement_type', models.CharField(choices=[('hard', 'Hard prerequisite'), ('supporting', 'Supporting prerequisite')], default='hard', max_length=20)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_relationships', to='schemes.prerequisiteconcept')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_relationships', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.sourcedocument')),
            ],
            options={
                'ordering': ['scheme_version', 'requirement_type', 'prerequisite'],
            },
        ),
        migrations.CreateModel(
            name='SchemeUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('extracted', 'Extracted'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('review_status', models.CharField(choices=[('review_required', 'Review required'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='review_required', max_length=30)),
                ('evidence_text', models.TextField()),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('predecessor_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_relationships_out', to='schemes.schemeversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sources.sourcedocument')),
                ('unlocked_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_relationships_in', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['predecessor_version', 'unlocked_version'],
            },
        ),
        migrations.AddIndex(
            model_name='prerequisiteconcept',
            index=models.Index(fields=['lifecycle_status', 'category'], name='schemes_pre_lifecyc_efbcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeprerequisite',
            index=models.Index(fields=['review_status', 'scheme_version'], name='schemes_sch_review__95ade3_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemeprerequisite',
            constraint=models.UniqueConstraint(fields=('scheme_version', 'prerequisite'), name='unique_scheme_version_prerequisite'),
        ),
        migrations.AddIndex(
            model_name='schemeunlock',
            index=models.Index(fields=['review_status', 'predecessor_version'], name='schemes_sch_review__a78401_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeunlock',
            index=models.Index(fields=['review_status', 'unlocked_version'], name='schemes_sch_review__d07591_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemeunlock',
            constraint=models.UniqueConstraint(fields=('predecessor_version', 'unlocked_version'), name='unique_scheme_version_unlock'),
        ),
    ]
