# Generated by Django 5.2.16 on 2026-07-20 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extractor_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_runs', to='documents.documentextraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('scheme', 'Scheme'), ('fund', 'Fund'), ('grant', 'Grant'), ('loan', 'Loan'), ('guarantee', 'Credit guarantee'), ('benefit', 'Benefit'), ('recognition', 'Recognition'), ('registration', 'Registration'), ('certificate', 'Certificate'), ('policy', 'Policy'), ('program', 'Program'), ('incubator', 'Incubator support'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('authority_name', models.CharField(blank=True, max_length=500)),
                ('ministry_name', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('objective_text', models.TextField(blank=True)),
                ('eligibility_text', models.TextField(blank=True)),
                ('benefits_text', models.TextField(blank=True)),
                ('application_text', models.TextField(blank=True)),
                ('required_documents_text', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True, max_length=2000)),
                ('application_url', models.URLField(blank=True, max_length=2000)),
                ('financial_amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financial_amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='needs_review', max_length=30)),
                ('raw_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='knowledge.knowledgeextractionrun')),
            ],
            options={
                'ordering': ['run', 'start_page', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocumentCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='required_document_candidates', to='documents.documentchunk')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_document_items', to='knowledge.schemecandidate')),
            ],
            options={
                'ordering': ['candidate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRuleCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=30)),
                ('value', models.JSONField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('human_text', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_rule_candidates', to='documents.documentchunk')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='knowledge.schemecandidate')),
            ],
            options={
                'ordering': ['candidate', 'field_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('title', 'Title'), ('summary', 'Summary'), ('objective', 'Objective'), ('eligibility', 'Eligibility'), ('benefit', 'Benefit'), ('application', 'Application'), ('document', 'Required document'), ('authority', 'Authority'), ('amount', 'Financial amount'), ('general', 'General')], default='general', max_length=30)),
                ('quote', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence', to='documents.documentchunk')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='knowledge.schemecandidate')),
            ],
            options={
                'ordering': ['candidate', 'page_number', 'chunk__chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='BenefitCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefit_candidates', to='documents.documentchunk')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_items', to='knowledge.schemecandidate')),
            ],
            options={
                'ordering': ['candidate', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStepCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_step_candidates', to='documents.documentchunk')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_steps', to='knowledge.schemecandidate')),
            ],
            options={
                'ordering': ['candidate', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeextractionrun',
            index=models.Index(fields=['status', '-created_at'], name='knowledge_k_status_e6dd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeextractionrun',
            index=models.Index(fields=['extraction', 'extractor_version'], name='knowledge_k_extract_de6603_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeextractionrun',
            constraint=models.UniqueConstraint(fields=('extraction', 'extractor_version'), name='unique_knowledge_extraction_version'),
        ),
        migrations.AddIndex(
            model_name='schemecandidate',
            index=models.Index(fields=['review_status', '-confidence'], name='knowledge_s_review__651f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='schemecandidate',
            index=models.Index(fields=['kind', 'review_status'], name='knowledge_s_kind_2abe96_idx'),
        ),
        migrations.AddIndex(
            model_name='schemecandidate',
            index=models.Index(fields=['run', 'start_page'], name='knowledge_s_run_id_e19ecc_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemecandidate',
            constraint=models.UniqueConstraint(fields=('run', 'stable_key'), name='unique_candidate_run_stable_key'),
        ),
        migrations.AddIndex(
            model_name='eligibilityrulecandidate',
            index=models.Index(fields=['field_name', 'operator'], name='knowledge_e_field_n_b76044_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityrulecandidate',
            index=models.Index(fields=['review_status', '-confidence'], name='knowledge_e_review__578a5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateevidence',
            constraint=models.UniqueConstraint(fields=('candidate', 'chunk', 'evidence_type'), name='unique_candidate_chunk_evidence_type'),
        ),
        migrations.AddConstraint(
            model_name='applicationstepcandidate',
            constraint=models.UniqueConstraint(fields=('candidate', 'step_number'), name='unique_candidate_application_step'),
        ),
    ]
