# Generated by Django 5.2.16 on 2026-07-20 15:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('schemes', '0002_authorityalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_title', models.CharField(blank=True, max_length=500)),
                ('classification', models.CharField(choices=[('unresolved', 'Unresolved'), ('canonical', 'Canonical scheme'), ('supporting', 'Supporting evidence'), ('duplicate', 'Duplicate candidate'), ('rejected', 'Rejected extraction')], default='unresolved', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='knowledge.schemecandidate')),
                ('primary_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_resolutions', to='knowledge.schemecandidate')),
                ('resolved_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_resolutions', to='schemes.authority')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classification', 'canonical_title', 'candidate'],
                'indexes': [models.Index(fields=['classification', '-resolved_at'], name='knowledge_c_classif_81a52b_idx'), models.Index(fields=['resolved_authority', 'classification'], name='knowledge_c_resolve_b2a4b8_idx')],
            },
        ),
    ]
