# Generated by Django 5.2.16 on 2026-07-20 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_candidateresolution'),
        ('schemes', '0002_authorityalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting')], default='primary', max_length=20)),
                ('publication_hash', models.CharField(db_index=True, max_length=64)),
                ('published_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='knowledge.schemecandidate')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_publications', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_publications', to='schemes.scheme')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_publications', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['-published_at', 'candidate'],
            },
        ),
        migrations.CreateModel(
            name='PublishedEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(max_length=30)),
                ('quote', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshots', to='knowledge.candidateevidence')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='knowledge.candidatepublication')),
            ],
            options={
                'ordering': ['publication', 'page_number', 'candidate_evidence'],
            },
        ),
        migrations.AddIndex(
            model_name='candidatepublication',
            index=models.Index(fields=['role', '-published_at'], name='knowledge_c_role_d33723_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepublication',
            index=models.Index(fields=['scheme', 'scheme_version'], name='knowledge_c_scheme__cb91c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatepublication',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('scheme_version',), name='unique_primary_candidate_publication'),
        ),
        migrations.AddConstraint(
            model_name='publishedevidence',
            constraint=models.UniqueConstraint(fields=('publication', 'candidate_evidence'), name='unique_publication_candidate_evidence'),
        ),
    ]
