# Generated by Django 5.2.16 on 2026-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_eligibilityrulecandidate_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecuration',
            name='canonical_application_steps',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatecuration',
            name='canonical_benefits',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatecuration',
            name='canonical_categories',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatecuration',
            name='canonical_required_documents',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatecuration',
            name='canonical_support_types',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
