# Generated by Django 5.2.16 on 2026-07-22 09:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_candidatecuration_canonical_application_steps_and_more'),
        ('schemes', '0002_authorityalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSchemeDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_key', models.CharField(max_length=150, unique=True)),
                ('dataset_name', models.CharField(max_length=500)),
                ('source_filename', models.CharField(max_length=500)),
                ('source_sheet', models.CharField(blank=True, max_length=250)),
                ('source_row_count', models.PositiveIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('normalization_version', models.CharField(max_length=100)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['dataset_key'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSchemeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=150)),
                ('scheme_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(db_index=True, max_length=500)),
                ('ministry', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('sector', models.TextField(blank=True)),
                ('startup_stage', models.JSONField(blank=True, default=list)),
                ('startup_type', models.TextField(blank=True)),
                ('industry', models.JSONField(blank=True, default=list)),
                ('central_state', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('funding_type', models.TextField(blank=True)),
                ('funding_amount', models.TextField(blank=True)),
                ('financial_instrument', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('women_eligible', models.CharField(blank=True, max_length=100)),
                ('sc_st_eligible', models.CharField(blank=True, max_length=100)),
                ('dpiit_required', models.CharField(blank=True, max_length=100)),
                ('startup_age_limit', models.TextField(blank=True)),
                ('revenue_criteria', models.TextField(blank=True)),
                ('tax_benefits', models.TextField(blank=True)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('application_process', models.TextField(blank=True)),
                ('official_website_label', models.TextField(blank=True)),
                ('official_application_url', models.TextField(blank=True)),
                ('source_portal', models.TextField(blank=True)),
                ('claimed_last_updated', models.CharField(blank=True, max_length=100)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_warnings', models.JSONField(blank=True, default=list)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('source_rows', models.JSONField(blank=True, default=list)),
                ('external_ids', models.JSONField(blank=True, default=list)),
                ('record_sha256', models.CharField(db_index=True, max_length=64)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='needs_review', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='knowledge.externalschemedataset')),
                ('matched_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_scheme_matches', to='knowledge.schemecandidate')),
                ('matched_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_scheme_matches', to='schemes.scheme')),
            ],
            options={
                'ordering': ['scheme_name', 'dataset', 'external_id'],
                'indexes': [models.Index(fields=['dataset', 'review_status', 'normalized_name'], name='knowledge_e_dataset_190af9_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'external_id'), name='unique_external_scheme_dataset_id')],
            },
        ),
    ]
