# Generated by Django 5.2.16 on 2026-07-20 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0002_crawlrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extractor_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_title', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('text_storage_key', models.CharField(blank=True, max_length=1000)),
                ('text_preview', models.TextField(blank=True)),
                ('text_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('section_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='sources.sourcedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=128)),
                ('character_start', models.PositiveIntegerField(default=0)),
                ('character_end', models.PositiveIntegerField(default=0)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentextraction')),
            ],
            options={
                'ordering': ['extraction', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='documentextraction',
            index=models.Index(fields=['status', '-created_at'], name='documents_d_status_435b17_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextraction',
            index=models.Index(fields=['source_document', 'extractor_version'], name='documents_d_source__1c592d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentextraction',
            constraint=models.UniqueConstraint(fields=('source_document', 'extractor_version'), name='unique_document_extractor_version'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['extraction', 'chunk_index'], name='documents_d_extract_9d2b41_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='documents_d_page_nu_2ab6c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('extraction', 'chunk_index'), name='unique_extraction_chunk_index'),
        ),
    ]
