# Generated by Django 5.2.16 on 2026-07-25 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0015_ml_engine_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(choices=[('kmeans', 'K-Means Cohort Clustering'), ('svm', 'SVM Scheme Success Ranker'), ('adaboost', 'AdaBoost Readiness Predictor'), ('isolation_forest', 'Isolation Forest Anomaly Detector'), ('random_forest', 'Random Forest Capital Forecaster'), ('tfidf', 'TF-IDF Hybrid Search Index'), ('dbscan', 'DBSCAN Scheme Deduplicator')], max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('model_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('retired', 'Retired'), ('failed', 'Failed')], default='training', max_length=20)),
                ('training_sample_count', models.PositiveIntegerField(default=0)),
                ('primary_metric_name', models.CharField(blank=True, max_length=64)),
                ('primary_metric_value', models.FloatField(blank=True, null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=512)),
                ('training_metadata', models.JSONField(blank=True, default=dict)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['model_type', '-model_version'],
                'indexes': [models.Index(fields=['model_type', 'status'], name='ml_engine_m_model_t_238cb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_type', 'model_version'), name='unique_model_type_version')],
            },
        ),
        migrations.CreateModel(
            name='MLFeatureStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_vector', models.JSONField(default=list)),
                ('feature_version', models.CharField(default='features-v1', max_length=64)),
                ('cohort_id', models.IntegerField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('readiness_improvement_probability', models.FloatField(blank=True, null=True)),
                ('startup_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_features', to='startups.startupprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cohort_id'], name='ml_engine_m_cohort__a2395c_idx'), models.Index(fields=['is_anomalous'], name='ml_engine_m_is_anom_34d944_idx')],
            },
        ),
    ]
