# Generated by Django 5.2.16 on 2026-07-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_ml_engine_integration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mlmodelregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('model_type',), name='unique_active_model_per_type'),
        ),
    ]
