# Generated by Django 5.2.16 on 2026-07-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_mlmodelregistry_unique_active_model_per_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelregistry',
            name='deployment_stage',
            field=models.CharField(choices=[('experimental', 'Experimental'), ('shadow', 'Shadow'), ('production', 'Production')], default='experimental', max_length=32),
        ),
        migrations.AddField(
            model_name='mlmodelregistry',
            name='production_approved',
            field=models.BooleanField(default=False),
        ),
    ]
