# Generated by Django 5.2.16 on 2026-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0003_mlmodelregistry_deployment_stage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mlmodelregistry',
            name='unique_active_model_per_type',
        ),
        migrations.AddConstraint(
            model_name='mlmodelregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('model_type', 'deployment_stage'), name='unique_active_model_per_type'),
        ),
    ]
