# Generated by Django 5.2.16 on 2026-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0004_remove_mlmodelregistry_unique_active_model_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelregistry',
            name='artifact_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
