# Generated by Django 5.2.16 on 2026-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0005_mlmodelregistry_artifact_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelregistry',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodelregistry',
            name='promoted_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mlmodelregistry',
            name='promotion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mlmodelregistry',
            name='replaced_model_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodelregistry',
            name='deployment_stage',
            field=models.CharField(choices=[('experimental', 'Experimental'), ('candidate', 'Candidate'), ('shadow', 'Shadow'), ('production', 'Production')], default='experimental', max_length=32),
        ),
    ]
